{% set name = "eland" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d1deb2836fcaaae2c8fbc02f196071b217eada3b065b606c87ed1190cb66d35

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - elasticsearch >=8.3,<9
    - pandas >=1.5,<3
    - matplotlib-base >=3.6
    - numpy >=1.2,<2
    - packaging
    - python >={{ python_min }},<3.13

test:
  requires:
    - scikit-learn
    - xgboost
    - lightgbm
    - python {{ python_min }}
  imports:
    - eland
    - eland.ml

about:
  home: https://eland.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python Client and Toolkit for DataFrames, Big Data, Machine Learning and ETL in Elasticsearch
  description: |
    Eland is a Elasticsearch client Python package to analyse, explore and manipulate data
    that resides in Elasticsearch. Where possible the package uses existing Python APIs and
    data structures to make it easy to switch between numpy, pandas, scikit-learn to their
    Elasticsearch powered equivalents. In general, the data resides in Elasticsearch and not
    in memory, which allows Eland to access large datasets stored in Elasticsearch.
  doc_url: https://eland.readthedocs.io
  dev_url: https://github.com/elastic/eland

extra:
  recipe-maintainers:
    - ezimuel
    - joshmock
    - pquentin
    - miguelgrinberg
