{% set name = "eland" %}
{% set version = "8.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4fdab96d0864166b20bf9cac39e42fe83fd57a48627c2e57bd2c9eda02f302a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<3.11
    - pip
  run:
    - elasticsearch >=8.3,<9
    - pandas >=1.5,<2
    - matplotlib-base >=3.6
    - numpy >=1.2,<2
    - packaging
    - python >=3.8,<3.11

test:
  requires:
    - scikit-learn
    - xgboost
    - lightgbm
  imports:
    - eland
    - eland.ml

about:
  home: https://eland.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python Client and Toolkit for DataFrames, Big Data, Machine Learning and ETL in Elasticsearch
  description: |
    Eland is a Elasticsearch client Python package to analyse, explore and manipulate data
    that resides in Elasticsearch. Where possible the package uses existing Python APIs and
    data structures to make it easy to switch between numpy, pandas, scikit-learn to their
    Elasticsearch powered equivalents. In general, the data resides in Elasticsearch and not
    in memory, which allows Eland to access large datasets stored in Elasticsearch.
  doc_url: https://eland.readthedocs.io
  dev_url: https://github.com/elastic/eland

extra:
  recipe-maintainers:
    - ezimuel
    - joshmock
    - stevedodson
    - pquentin
