{% set name = "eland" %}
{% set version = "7.9.1a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3efba79963fb3222f52184ec382fb02b7d52af3e0295e0344038395c93d5d4bb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - elasticsearch >=7.7.0,<8
    - pandas >=1.0.0
    - matplotlib-base
    - python

test:
  requires:
    - scikit-learn
    - xgboost
    - lightgbm
  imports:
    - eland
    - eland.ml

about:
  home: https://eland.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python Client and Toolkit for DataFrames, Big Data, Machine Learning and ETL in Elasticsearch
  description: |
    Eland is a Elasticsearch client Python package to analyse, explore and manipulate data
    that resides in Elasticsearch. Where possible the package uses existing Python APIs and
    data structures to make it easy to switch between numpy, pandas, scikit-learn to their
    Elasticsearch powered equivalents. In general, the data resides in Elasticsearch and not
    in memory, which allows Eland to access large datasets stored in Elasticsearch.
  doc_url: https://eland.readthedocs.io
  dev_url: https://github.com/elastic/eland

extra:
  recipe-maintainers:
    - sethmlarson
    - stevedodson
